server:
  port: 8082
spring:
  application:
    name: admin
  profiles:
    active: dev
  #设定ftl文件路径
  freemarker:
    templateLoaderPath: classpath:/templates/
  #设定静态文件路径，js,css等
  mvc:
    staticPathPattern: /static/**
