server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-logo:
      path: /logoapi/**
      serviceId: logo
#    api-comment:
#      path: /api/comment/**
#      serviceId: comment
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
