server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-logo:
      path: /logo/**
      serviceId: logo
    api-admin:
      path: /admin/**
      serviceId: admin
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
security:
    user:
        password: user #直接登录时的密码
    ignored: /
    sessions: never # session策略
    oauth2: 
        sso: 
            loginPath: /login   # 登录路径
        client:
            clientId: 95dd2fdd98efe5e03784
            clientSecret: 33322a04361253070bdd50b28bb1aabaaef3ae83
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
        resource:
            userInfoUri: https://api.github.com/user
            preferTokenInfo: false
